"""add_system_alerts_and_storage_logs

Revision ID: 36541e3ffc19
Revises: ceb0b0ced4a9
Create Date: 2026-09-12 18:40:20.269210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36541e3ffc19'
down_revision: Union[str, Sequence[str], None] = 'ceb0b0ced4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('target_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_logs_operation'), 'storage_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_storage_logs_timestamp'), 'storage_logs', ['timestamp'], unique=False)
    op.create_table('system_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_alerts_alert_type'), 'system_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_system_alerts_created_at'), 'system_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_alerts_is_acknowledged'), 'system_alerts', ['is_acknowledged'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_system_alerts_is_acknowledged'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_created_at'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_alert_type'), table_name='system_alerts')
    op.drop_table('system_alerts')
    op.drop_index(op.f('ix_storage_logs_timestamp'), table_name='storage_logs')
    op.drop_index(op.f('ix_storage_logs_operation'), table_name='storage_logs')
    op.drop_table('storage_logs')
    # ### end Alembic commands ###
