"""compliance_and_audit

Revision ID: 5c90b75f2972
Revises: fceaccf2bcff
Create Date: 2026-06-15 19:55:24.933882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c90b75f2972'
down_revision: Union[str, Sequence[str], None] = 'fceaccf2bcff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('performed_by', sa.String(length=50), nullable=False),
    sa.Column('target_phone', sa.String(length=15), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('retain_until', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    # Data migration to populate existing records
    op.execute("UPDATE documents SET retain_until = policy_end_date + INTERVAL '5 years'")
    op.execute("UPDATE documents SET is_deleted = FALSE")
    
    # Set to NOT NULL
    op.alter_column('documents', 'retain_until', nullable=False)
    op.alter_column('documents', 'is_deleted', nullable=False)
    
    # op.drop_index(op.f('idx_documents_phone'), table_name='documents')
    # op.drop_index(op.f('idx_documents_type'), table_name='documents')
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_documents_retain_until'), 'documents', ['retain_until'], unique=False)
    # op.drop_index(op.f('idx_users_phone'), table_name='users')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_phone'), 'users', ['phone_number'], unique=False)
    op.drop_index(op.f('ix_documents_retain_until'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.create_index(op.f('idx_documents_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('idx_documents_phone'), 'documents', ['phone_number'], unique=False)
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'is_deleted')
    op.drop_column('documents', 'retain_until')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
