"""remove_redundant_indexes

Revision ID: ceb0b0ced4a9
Revises: a2ab93597200
Create Date: 2026-06-15 23:37:46.676835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb0b0ced4a9'
down_revision: Union[str, Sequence[str], None] = 'a2ab93597200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.drop_index(op.f('ix_documents_policy_end_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_policy_start_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_vehicle_reg_no'), table_name='documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_vehicle_reg_no'), 'documents', ['vehicle_reg_no'], unique=False)
    op.create_index(op.f('ix_documents_policy_start_date'), 'documents', ['policy_start_date'], unique=False)
    op.create_index(op.f('ix_documents_policy_end_date'), 'documents', ['policy_end_date'], unique=False)
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    # ### end Alembic commands ###
