"""drop_otp_store_table

Revision ID: e8870016ae16
Revises: 36541e3ffc19
Create Date: 2026-09-12 18:52:34.313774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8870016ae16'
down_revision: Union[str, Sequence[str], None] = '36541e3ffc19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otp_store')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_store',
    sa.Column('vehicle_reg_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('vehicle_reg_no', name=op.f('otp_store_pkey'))
    )
    # ### end Alembic commands ###
